name: i18n_lite
description: A new Flutter project.
  
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  
  # url_launcher: ^5.1.2
  cupertino_icons: ^1.0.2
  url_launcher: ^5.2.7
    
dev_dependencies:
  flutter_test:
    sdk: flutter
    
dependency_overrides:
  intl: any
  intl_translation: any    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


# # /old yaml 2019
# name: ethsync19
# description: A new flutter ethereum synchronisation project

# # The following defines the version and build number for your application.
# # A version number is three numbers separated by dots, like 1.2.43
# # followed by an optional build number separated by a +.
# # Both the version and the builder number may be overridden in flutter
# # build by specifying --build-name and --build-number, respectively.
# # In Android, build-name is used as versionName while build-number used as versionCode.
# # Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# # In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# # Read more about iOS versioning at
# # https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# version: 1.0.0+1

# environment:
#   sdk: ">=2.1.0 <3.0.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   flutter_localizations:
#     sdk: flutter
#   qr_flutter: ^2.1.0+55
#   # qr_code_scanner: ^0.0.11
#   # flutter_barcode_scanner: ^0.1.5
#   qrcode_reader: ^0.4.4
#   flutter_linkify: ^2.1.0
#   url_launcher: ^5.1.2
#   share: ^0.6.2+1
#   flutter_i18n: ^0.6.3
#   intl: ^0.16.1
#   intl_translation: ^0.17.5
#   # connectivity/: ^0.4.3+6
#   # path_provider: ^1.1.2
#   extended_image: ^0.5.8
#   # extended_image_library: ^0.1.4
#   cached_network_image: ^1.1.1
#   # flutter_screenutil: ^0.5.3
#   flutter_advanced_networkimage: ^0.5.0
#   flutter_svg: ^0.13.1
#   # cloud_firestore: ^0.8.2     # new
#   cloud_firestore: ^0.12.9
#   # firebase_core: ^0.4.0+1
#   # fluttertoast: ^3.1.0
#   oktoast: ^2.1.7
#   # firebase_admob: ^0.9.0+4
#   # admob_flutter: ^0.3.1
#   # flutter_native_splash: ^0.1.6
#   # flutter_web_view: ^0.0.6
#   flutter_web_browser: ^0.11.0
#   flutter_native_web: ^1.0.3

#   # The following adds the Cupertino Icons font to your application.
#   # Use with the CupertinoIcons class for iOS style icons.
#   cupertino_icons: ^0.1.2

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_native_splash: ^0.1.7

# flutter_native_splash:
#   image: assets/splash.png
#   color: "#000000"

# # For information on the generic Dart part of this file, see the
# # following page: https://dart.dev/tools/pub/pubspec

# # The following section is specific to Flutter.
# flutter:

#   # The following line ensures that the Material Icons font is
#   # included with your application, so that you can use the icons in
#   # the material Icons class.
#   uses-material-design: true

#   # To add assets to your application, add an assets section, like this:
#   # assets:
#   #  - images/a_dot_burr.jpeg
#   #  - images/a_dot_ham.jpeg

#   assets:
#    - assets/ethBullet.png
#    - assets/etcBullet.png
#    - assets/duIcon.png
#    - assets/wallpaper-homestead.jpg
#    - assets/ethSync.jpg
#    - assets/logo.png
#    - assets/ethGreenHelp.png
#    - assets/logoHyg.png
#    - assets/logoCli.png
#    - assets/gethTerm.png
#    - assets/devcon1.png
#    - assets/etceth-asia.jpg
#    - assets/bleachBitSwap.png
#    - assets/geth1win.png
#    - assets/geth2win.png
#    - assets/kraken-eth-eur.png
#    - assets/ethStackExchange.png
#    - assets/ethereum_Web_Xi.png
#    - assets/ethereum_youtube.png
#    - assets/loading.gif
#    - assets/yanetSwimsuit.gif
#    - assets/USStates.svg
#    - assets/go-download-website.png
#    - assets/footer-gopher.jpg
#    - assets/go-env.png
#    - assets/go-3-folders.png
#    - assets/go-hello.png
#    - assets/go-build-install.png
#    - assets/geth-web.png
#    - assets/gethdl-os.png
#    - assets/geth-install-help.png
#    - assets/geth-command-help.png
#    - assets/go-help-1.png
#    - assets/go-help-2.png
#    - assets/go-build-run-local.png
#    - assets/go-install-systemwide.png
#    - assets/github-go-ethereum-list.png
#    - assets/which-geth-list.png
#    - assets/geth-help-1.png
#    - assets/geth-help-2.png
#    - assets/geth-help-3.png
#    - assets/geth-help-4.png
#    - assets/geth-help-5.png
#    - assets/geth-help-6.png
#    - assets/geth-syncmode-begin.png
#    - assets/geth-blockchain-p2p.png
#    - assets/ethsync-complete-closed.png
#    - assets/blockchain-size.png

#   # An image asset can refer to one or msore resolution-specific "variants", see
#   # https://flutter.dev/assets-and-images/#resolution-aware.

#   # For details regarding adding assets from package dependencies, see
#   # https://flutter.dev/assets-and-images/#from-packages

#   # To add custom fonts to your application, add a fonts section here,
#   # in this "flutter" section. Each entry in this list should have a
#   # "family" key with the font family name, and a "fonts" key with a
#   # list giving the asset and other descriptors for the font. For
#   # example:
#   # fonts:
#   #   - family: Schyler
#   #     fonts:
#   #       - asset: fonts/Schyler-Regular.ttf
#   #       - asset: fonts/Schyler-Italic.ttf
#   #         style: italic
#   #   - family: Trajan Pro
#   #     fonts:
#   #       - asset: fonts/TrajanPro.ttf
#   #       - asset: fonts/TrajanPro_Bold.ttf
#   #         weight: 700
#   #
#   # For details regarding fonts from package dependencies,
#   # see https://flutter.dev/custom-fonts/#from-packages
